name: Copy File to OneDrive on Commit to Main

on:
    push:
        branches:
            - main

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --configuration Release

    - name: List project files
      run: ls -R

    # Run the .NET application
    - name: Run .NET Application
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        USER_PRINCIPAL_NAME: ${{ vars.USER_PRINCIPAL_NAME }}
        UPLOAD_PATH: ${{ vars.UPLOAD_PATH }}
        REPO_NAME: ${{ vars.REPO_NAME }}
        FILE_PATH: ${{ vars.FILE_PATH }}
      run: dotnet run
